# Generated by Django 5.2.6 on 2025-09-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('counsellor', 'Counselor'), ('admin', 'Admin'), ('anonymous', 'Anonymous')], default='student', max_length=20),
        ),
    ]
