# Generated by Django 5.2.6 on 2026-04-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('counsellor', 'Counselor'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
